---
title: "SAS home"
---

SAS is statistical software. It dates from 1969 (when the alternative to using it was writing your own code in Fortran). Its strength is that it does standard analyses in standard ways (that will continue to work many years into the future). There is typically less actual coding than is required to accomplish the same task in R, but you don't get the same flexibility to explore that you get in R. As a result, it finds heavy use in companies and institutions where the same analysis is done repeatedly on new data. 

Sometimes I teach SAS in STAC32/STAC33, sometimes not. This website has some notes and code that will get you started with SAS, at the level of STAC32 or STAC33 (in fact, using a lot of the same examples), including getting connected to the online version of SAS in the first place. There is also "SAS University Edition" that runs (in a virtual machine) on your own computer, though support for that is being withdrawn, and there also seem to be some ways of running SAS in a [Jupyter Notebook](https://jupyter.org/) (as if it were Python).

Use the top bar to get to my [lecture slides](slides-sas.pdf) and [code](code.html). There aren't any lecture videos yet, though there might be eventually. [PASI-SAS](pasi-sas.pdf) is a collection of worked problems with solutions.

If you have taken STAD29, which has been taught with R for a number of years now, you might recognize some of the data sets [in here](https://www.utsc.utoronto.ca/~butler/d29/sasexamples.html), with code to do the corresponding examples in SAS.